### ISSUE TITLE
Not able to run BUSSide

### ISSUE THREAD

**Issue by nikkisstuff** [BSidesCbr/BUSSide#9]
I have just installed a fresh version of kali and when i try to run the busside python file i get the following error. 

$ sudo ./busside.py /dev/ttyUSB0                                       1 ⨯
Traceback (most recent call last):
  File "./busside.py", line 6, in <module>
    import bs_i2c
  File "/home/nikki/BUSSide/Client/bs_i2c.py", line 3, in <module>
    import bs
  File "/home/nikki/BUSSide/Client/bs.py", line 7, in <module>
    import serial
ImportError: No module named serial

**Comment by silviocesare** [comment]
You will need to install the python-serial package. Also note to use python2 and not 3.

**Comment by nikkisstuff** [comment]
Thanks that has fixed it
